CREATE EXTERNAL TABLE `truvalue_ttm_volume`(
  `date` date,
  `isin` string,
  `organizationtvlid` string,
  `instrumenttvlid` string,
  `organizationname` string,
  `ticker` string,
  `allcategories_categoryvolumettm` double,
  `materiality_categoryvolumettm` double,
  `allcategories_articlevolumettm` double,
  `materiality_articlevolumettm` double,
  `accessandaffordability_categoryvolumettm` double,
  `airquality_categoryvolumettm` double,
  `businessethics_categoryvolumettm` double,
  `businessmodelresilience_categoryvolumettm` double,
  `competitivebehavior_categoryvolumettm` double,
  `criticalincidentriskmanagement_categoryvolumettm` double,
  `customerprivacy_categoryvolumettm` double,
  `customerwelfare_categoryvolumettm` double,
  `datasecurity_categoryvolumettm` double,
  `ecologicalimpacts_categoryvolumettm` double,
  `employeeengagementdiversityandinclusion_categoryvolumettm` double,
  `employeehealthandsafety_categoryvolumettm` double,
  `energymanagement_categoryvolumettm` double,
  `ghgemissions_categoryvolumettm` double,
  `humanrightsandcommunityrelations_categoryvolumettm` double,
  `laborpractices_categoryvolumettm` double,
  `managementofthelegalandregulatoryenvironment_categoryvolumettm` double,
  `materialssourcingandefficiency_categoryvolumettm` double,
  `physicalimpactsofclimatechange_categoryvolumettm` double,
  `productdesignandlifecyclemanagement_categoryvolumettm` double,
  `productqualityandsafety_categoryvolumettm` double,
  `sellingpracticesandproductlabeling_categoryvolumettm` double,
  `supplychainmanagement_categoryvolumettm` double,
  `systemicriskmanagement_categoryvolumettm` double,
  `wasteandhazardousmaterialsmanagement_categoryvolumettm` double,
  `waterandwastewatermanagement_categoryvolumettm` double,
  `accessandaffordability_impactpercentagettm` double,
  `airquality_impactpercentagettm` double,
  `businessethics_impactpercentagettm` double,
  `businessmodelresilience_impactpercentagettm` double,
  `competitivebehavior_impactpercentagettm` double,
  `criticalincidentriskmanagement_impactpercentagettm` double,
  `customerprivacy_impactpercentagettm` double,
  `customerwelfare_impactpercentagettm` double,
  `datasecurity_impactpercentagettm` double,
  `ecologicalimpacts_impactpercentagettm` double,
  `employeeengagementdiversityandinclusion_impactpercentagettm` double,
  `employeehealthandsafety_impactpercentagettm` double,
  `energymanagement_impactpercentagettm` double,
  `ghgemissions_impactpercentagettm` double,
  `humanrightsandcommunityrelations_impactpercentagettm` double,
  `laborpractices_impactpercentagettm` double,
  `managementofthelegalandregulatoryenvironment_impactpercentagettm` double,
  `materialssourcingandefficiency_impactpercentagettm` double,
  `physicalimpactsofclimatechange_impactpercentagettm` double,
  `productdesignandlifecyclemanagement_impactpercentagettm` double,
  `productqualityandsafety_impactpercentagettm` double,
  `sellingpracticesandproductlabeling_impactpercentagettm` double,
  `supplychainmanagement_impactpercentagettm` double,
  `systemicriskmanagement_impactpercentagettm` double,
  `wasteandhazardousmaterialsmanagement_impactpercentagettm` double,
  `waterandwastewatermanagement_impactpercentagettm` double,
  `cppib_sec_id` bigint,
  `df_meta_epoch` string,
  `df_meta_file_name` string,
  `df_meta_system_process_date` timestamp,
  `df_meta_run_date` string,
  `df_meta_job_id` string)
PARTITIONED BY (
  `file_date` string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://cppib-data-fabric-trusted-${env}/truvalue/truvalue_ttm_volume'
