CREATE EXTERNAL TABLE `trucost_env_cpucu`(
  `tcuid` string,
  `company` string,
  `isin` string,
  `financial_year` string,
  `gics_sector_code` string,
  `gics_sector_name` string,
  `gics_industry_group_code` string,
  `gics_industry_group_name` string,
  `gics_industry_code` string,
  `gics_industry_name` string,
  `gics_sub_industry_code` string,
  `gics_sub_industry_name` string,
  `gics_description` string,
  `country` string,
  `carbon_scope_1_tonnes_co2e` string,
  `carbon_scope_2_tonnes_co2e` string,
  `carbon_scope_3_tonnes_co2e` string,
  `carbon_direct_tonnes_co2e` string,
  `carbon_first_tier_indirect_tonnes_co2e` string,
  `carbon_direct_first_tier_indirect_tonnes_co2e` string,
  `water_direct_cooling_cubic_meter` string,
  `water_direct_process_cubic_meter` string,
  `water_purchased_cubic_meter` string,
  `water_direct_purchased_cubic_meter` string,
  `waste_landfill_tonnes` string,
  `waste_incineration_tonnes` string,
  `waste_nuclear_tonnes` string,
  `waste_recycled_tonnes` string,
  `carbon_intensity_scope_1_tonnes_co2e_usd_mn` string,
  `carbon_intensity_scope_2_tonnes_co2e_usd_mn` string,
  `carbon_intensity_scope_3_tonnes_co2e_usd_mn` string,
  `carbon_intensity_direct_tonnes_co2e_usd_mn` string,
  `carbon_intensity_first_tier_indirect_tonnes_co2e_usd_mn` string,
  `carbon_intensity_direct_first_tier_indirect_tonnes_co2e_usd_mn` string,
  `water_intensity_direct_cooling_cubic_meter_usd_mn` string,
  `water_intensity_direct_process_cubic_meter_usd_mn` string,
  `water_intensity_purchased_cubic_meter_usd_mn` string,
  `water_intensity_direct_purchased_cubic_meter_usd_mn` string,
  `waste_intensity_landfill_tonnes_usd_mn` string,
  `waste_intensity_incineration_tonnes_usd_mn` string,
  `waste_intensity_nuclear_tonnes_usd_mn` string,
  `waste_intensity_recycled_tonnes_usd_mn` string,
  `total_direct_usd_mn` string,
  `total_indirect_usd_mn` string,
  `total_direct_indirect_usd_mn` string,
  `ghg_direct_usd_mn` string,
  `ghg_indirect_usd_mn` string,
  `ghg_total_usd_mn` string,
  `water_direct_usd_mn` string,
  `water_indirect_usd_mn` string,
  `water_total_usd_mn` string,
  `waste_direct_usd_mn` string,
  `waste_indirect_usd_mn` string,
  `waste_total_usd_mn` string,
  `land_and_water_pollutants_direct_usd_mn` string,
  `land_and_water_pollutants_indirect_usd_mn` string,
  `land_and_water_pollutants_total_usd_mn` string,
  `air_pollutants_direct_usd_mn` string,
  `air_pollutants_indirect_usd_mn` string,
  `air_pollutants_total_usd_mn` string,
  `natural_resource_use_direct_usd_mn` string,
  `natural_resource_use_indirect_usd_mn` string,
  `natural_resource_use_total_usd_mn` string,
  `total_direct_impact_ratio` string,
  `total_indirect_impact_ratio` string,
  `total_direct_indirect_impact_ratio` string,
  `ghg_direct_impact_ratio` string,
  `ghg_indirect_impact_ratio` string,
  `ghg_total_impact_ratio` string,
  `water_direct_impact_ratio` string,
  `water_indirect_impact_ratio` string,
  `water_total_impact_ratio` string,
  `waste_direct_impact_ratio` string,
  `waste_indirect_impact_ratio` string,
  `waste_total_impact_ratio` string,
  `land_and_water_pollutants_direct_impact_ratio` string,
  `land_and_water_pollutants_indirect_impact_ratio` string,
  `land_and_water_pollutants_total_impact_ratio` string,
  `air_pollutants_direct_impact_ratio` string,
  `air_pollutants_indirect_impact_ratio` string,
  `air_pollutants_total_impact_ratio` string,
  `natural_resource_use_direct_impact_ratio` string,
  `natural_resource_use_indirect_impact_ratio` string,
  `natural_resource_use_total_impact_ratio` string,
  `carbon_disclosure` string,
  `carbon_weighted_disclosure` string,
  `water_weighted_disclosure` string,
  `waste_weighted_disclosure` string,
  `revenue_usd_mn` string,
  `accounting_year_end` string,
  `figurerestate` string,
  `effectivedate` string,
  `df_meta_epoch` string,
  `df_meta_system_process_date` string,
  `df_meta_file_name` string,
  `df_meta_extracted_date` string)
PARTITIONED BY (
  `df_meta_run_date` string,
  `df_meta_job_id` string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://cppib-data-fabric-raw-${env}/trucost/env_cpucu'